# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:

 # Container registry service connection established during pipeline creation
  dockerfilePath: '**/docker/shipping/Dockerfile'
  tag: '$(Build.BuildId)'
  serviceName: shipping

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: microservicesdemo
      type: github
      name: northpoint/microservices-demo
      endpoint: github-svcconn

stages:
- stage: MavenPackage
  displayName: Maven Package stage
  jobs:
    - template: /pipeline-templates/java-build.yaml@microservicesdemo
      parameters:
        mavenPomFile: 'pom.xml'
        jdkVersionOption: 1.8
        goals: package

- stage: DockerBuild
  displayName: Docker Build & Push
  jobs:
    - template: /pipeline-templates/docker-builddeploy-pipeline.yaml@microservicesdemo  # Template reference
      parameters:
        tag: $(tag)
        acrRepo: $(serviceName)
        dockerfilePath: $(dockerfilePath)
        artifact: jar
        buildContext: $(Build.Repository.LocalPath)
      
      
- stage: HelmDeploy
  displayName: Helm Deploy
  jobs:
  - template: /pipeline-templates/helm-deploy-pipeline.yaml@microservicesdemo
    parameters:
      serviceName: $(serviceName)
      image: $(serviceName):$(tag)
